import { v4 as uuidv4 } from 'uuid';

import type { Movie } from '../types/entities/Movie.ts';

export const moviesData: Movie[] = [
  {
    id: uuidv4(),
    name: 'Престиж',
    originalName: 'The Prestige',
    year: 2006,
    countries: ['Великобритания', 'США'],
    genres: ['триллер', 'фантастика', 'драма', 'детектив'],
    director: 'Кристофер Нолан',
    rating: 8.5,
    image: '/movies/prestige.webp',
  },
  {
    id: uuidv4(),
    name: 'Дюна',
    originalName: 'Dune',
    year: 2021,
    countries: ['США', 'Канада', 'Венгрия'],
    genres: ['фантастика', 'боевик', 'драма', 'приключения'],
    director: 'Дени Вильнёв',
    rating: 7.7,
    image: '/movies/dune.webp',
  },
  {
    id: uuidv4(),
    name: 'Дюна: Часть вторая',
    originalName: 'Dune: Part Two',
    year: 2024,
    countries: ['США', 'Канада', 'ОАЭ', 'Венгрия', 'Италия', 'Новая Зеландия', 'Иордания', 'Гамбия'],
    genres: ['фантастика', 'боевик', 'драма', 'приключения'],
    director: 'Дени Вильнёв',
    rating: 7.7,
    image: '/movies/dune2.webp',
  },
  {
    id: uuidv4(),
    name: 'Бегущий по лезвию 2049',
    originalName: 'Blade Runner 2049',
    year: 2017,
    countries: ['США', 'Канада', 'Испания'],
    genres: ['фантастика', 'боевик', 'триллер', 'драма'],
    director: 'Дени Вильнёв',
    rating: 7.8,
    image: '/movies/bladerunner.jpg',
  },
  {
    id: uuidv4(),
    name: 'Шоу Трумана',
    originalName: 'The Truman Show',
    year: 1998,
    countries: ['США'],
    genres: ['драма', 'комедия'],
    director: 'Питер Уир',
    rating: 8.3,
    image: '/movies/truman.jpg',
  },
];
